/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TwinRouteImport } from './routes/twin'
import { Route as StrategistRouteImport } from './routes/strategist'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as PatrolRouteImport } from './routes/patrol'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as DiversionRouteImport } from './routes/diversion'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as BriefRouteImport } from './routes/brief'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsNewRouteImport } from './routes/events.new'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'

const TwinRoute = TwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategistRoute = StrategistRouteImport.update({
  id: '/strategist',
  path: '/strategist',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrolRoute = PatrolRouteImport.update({
  id: '/patrol',
  path: '/patrol',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const DiversionRoute = DiversionRouteImport.update({
  id: '/diversion',
  path: '/diversion',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefRoute = BriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/brief': typeof BriefRoute
  '/demo': typeof DemoRoute
  '/diversion': typeof DiversionRoute
  '/learn': typeof LearnRoute
  '/patrol': typeof PatrolRoute
  '/replay': typeof ReplayRoute
  '/resources': typeof ResourcesRoute
  '/strategist': typeof StrategistRoute
  '/twin': typeof TwinRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/new': typeof EventsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/brief': typeof BriefRoute
  '/demo': typeof DemoRoute
  '/diversion': typeof DiversionRoute
  '/learn': typeof LearnRoute
  '/patrol': typeof PatrolRoute
  '/replay': typeof ReplayRoute
  '/resources': typeof ResourcesRoute
  '/strategist': typeof StrategistRoute
  '/twin': typeof TwinRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/new': typeof EventsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/brief': typeof BriefRoute
  '/demo': typeof DemoRoute
  '/diversion': typeof DiversionRoute
  '/learn': typeof LearnRoute
  '/patrol': typeof PatrolRoute
  '/replay': typeof ReplayRoute
  '/resources': typeof ResourcesRoute
  '/strategist': typeof StrategistRoute
  '/twin': typeof TwinRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/new': typeof EventsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/brief'
    | '/demo'
    | '/diversion'
    | '/learn'
    | '/patrol'
    | '/replay'
    | '/resources'
    | '/strategist'
    | '/twin'
    | '/events/$eventId'
    | '/events/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/brief'
    | '/demo'
    | '/diversion'
    | '/learn'
    | '/patrol'
    | '/replay'
    | '/resources'
    | '/strategist'
    | '/twin'
    | '/events/$eventId'
    | '/events/new'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/brief'
    | '/demo'
    | '/diversion'
    | '/learn'
    | '/patrol'
    | '/replay'
    | '/resources'
    | '/strategist'
    | '/twin'
    | '/events/$eventId'
    | '/events/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BriefRoute: typeof BriefRoute
  DemoRoute: typeof DemoRoute
  DiversionRoute: typeof DiversionRoute
  LearnRoute: typeof LearnRoute
  PatrolRoute: typeof PatrolRoute
  ReplayRoute: typeof ReplayRoute
  ResourcesRoute: typeof ResourcesRoute
  StrategistRoute: typeof StrategistRoute
  TwinRoute: typeof TwinRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsNewRoute: typeof EventsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/twin': {
      id: '/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof TwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategist': {
      id: '/strategist'
      path: '/strategist'
      fullPath: '/strategist'
      preLoaderRoute: typeof StrategistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrol': {
      id: '/patrol'
      path: '/patrol'
      fullPath: '/patrol'
      preLoaderRoute: typeof PatrolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diversion': {
      id: '/diversion'
      path: '/diversion'
      fullPath: '/diversion'
      preLoaderRoute: typeof DiversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief': {
      id: '/brief'
      path: '/brief'
      fullPath: '/brief'
      preLoaderRoute: typeof BriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BriefRoute: BriefRoute,
  DemoRoute: DemoRoute,
  DiversionRoute: DiversionRoute,
  LearnRoute: LearnRoute,
  PatrolRoute: PatrolRoute,
  ReplayRoute: ReplayRoute,
  ResourcesRoute: ResourcesRoute,
  StrategistRoute: StrategistRoute,
  TwinRoute: TwinRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  EventsNewRoute: EventsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
